export const SIGNIN_REQUESTED = 'SIGNIN_REQUESTED'
export const SIGNIN_SUCCEEDED = 'SIGNIN_SUCCEEDED'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'

export const SIGNOUT_REQUESTED = 'SIGNOUT_REQUESTED'
